#!/bin/bash
set -eu

pushd $(dirname "${BASH_SOURCE[0]}")

# bosh cli
sudo wget https://github.com/cloudfoundry/bosh-cli/releases/download/v5.5.1/bosh-cli-5.5.1-linux-amd64 -O bosh
sudo chmod 755 bosh
sudo mv bosh /var/vcap/packages/jumpbox/bin/bosh

# fly5
sudo wget https://github.com/concourse/concourse/releases/download/v5.3.0/fly-5.3.0-linux-amd64.tgz -O fly5.tgz && tar xvf fly5.tgz && rm -f fly5.tgz
sudo mv fly /usr/local/bin/fly5
sudo chmod 755 /usr/local/bin/fly5

# om-linux
sudo wget https://github.com/pivotal-cf/om/releases/download/0.54.0/om-linux -O /usr/local/bin/om
sudo chmod 755 /usr/local/bin/om

# tile-config-generator
sudo wget https://github.com/pivotalservices/tile-config-generator/releases/download/v0.0.14/tile-config-generator-linux -O /usr/local/bin/tile-config-generator
sudo chmod 755 /usr/local/bin/tile-config-generator

# yaml-patch
sudo wget https://github.com/krishicks/yaml-patch/releases/download/v0.0.10/yaml_patch_linux -O /usr/local/bin/yaml-patch
sudo chmod 755 /usr/local/bin/yaml-patch

# yaml-diff
sudo wget https://github.com/sahilm/yamldiff/releases/download/0.1.0/yamldiff-v0.1.0-linux-amd64 -O /usr/local/bin/yaml-diff
sudo chmod 755 /usr/local/bin/yaml-diff

# cliaas
sudo wget https://github.com/pivotal-cf/cliaas/releases/download/v0.2.7/cliaas-linux -O /usr/local/bin/cliaas
sudo chmod 755 /usr/local/bin/cliaas

# gron
wget https://github.com/tomnomnom/gron/releases/download/v0.6.0/gron-linux-amd64-0.6.0.tgz -O /tmp/gron.tgz
sudo tar zxvf /tmp/gron.tgz -C /usr/local/bin/
sudo chmod 755 /usr/local/bin/gron

# minio
sudo wget https://dl.minio.io/server/minio/release/linux-amd64/minio -O /usr/local/bin/minio
sudo chmod 755 /usr/local/bin/minio

# mysql-client
sudo apt-get install -y mysql-client 

# python 2.7
sudo sudo apt install python2.7 python-pip -y
sudo pip2 install --upgrade pip

# pip3
sudo apt install -y python3-pip
sudo pip3 install --upgrade pip

# rabbitmq-collect-env 
wget https://raw.githubusercontent.com/rabbitmq/support-tools/master/scripts/rabbitmq-collect-env 
chmod 755 rabbitmq-collect-env
sudo mv rabbitmq-collect-env /usr/local/bin/rabbitmq-collect-env

# texplate
sudo wget https://github.com/pivotal-cf/texplate/releases/download/v0.3.0/texplate_linux_amd64 -O /usr/local/bin/texplate
sudo chmod 755 /usr/local/bin/texplate

# tcpflood
sudo wget https://github.com/nshrest/jumpbox-packages/releases/download/v1.0.0/tcpflood -O /usr/local/bin/tcpflood
sudo chmod 755 /usr/local/bin/tcpflood

# goblob
sudo wget https://github.com/pivotal-cf/goblob/releases/download/v1.4.0/goblob-linux -O /usr/local/bin/goblob
sudo chmod 755 /usr/local/bin/goblob

# govc
wget https://github.com/vmware/govmomi/releases/download/v0.20.0/govc_linux_amd64.gz -O govc_linux_amd64.gz
gzip -d govc_linux_amd64.gz
chmod +x govc_linux_amd64
sudo mv govc_linux_amd64 /usr/local/bin/govc
rm -f govc_linux_amd64.gz

# vegeta (HTTP load testing tool and library)
wget https://github.com/tsenart/vegeta/releases/download/cli%2Fv12.5.1/vegeta-12.5.1-linux-amd64.tar.gz -O vegeta.tar.gz
tar zxvf vegeta.tar.gz
chmod 755 vegeta
sudo mv vegeta /usr/local/bin/vegeta
rm -rf vegeta.tar.gz CHANGELOG LICENSE README.md

# kubectl
sudo apt-get update
sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubectl

# cfmenu
if [ ! -d ../pcf-admins ];then
  git clone https://github.com/nshrest/pcf-admins ../pcf-admins
fi

# url timings
if [ ! -d ../url-timings ]; then
  git clone https://github.com/kajic/url-timings ../url-timings
  cd ../url-timings
  sudo pip2 install gevent tabulate Cython docopt
  cd -
fi

popd

